#!/usr/bin/bash

# install_ufw
#
# Installs and enables ufw (uncomplicated firewall) with a simple ruleset and
# also installs gufw (a gui frontend for ufw)
install_ufw(){

	sudo apt-get install -y ufw
	sudo ufw enable
	sudo ufw status --verbose
	sudo apt-get install -y gufw
	gufw &
}

install_ufw