#!/usr/bin/bash

function install_jenkins(){
    # Download the Jenkins key
    wget https://pkg.jenkins.io/debian-stable/jenkins.io.key
    
    # Add the key
    sudo apt-key add jenkins.io.key
    
    # Add the Jenkins repository
    echo "deb https://pkg.jenkins.io/debian-stable binary/" | tee /etc/apt/sources.list.d/jenkins.list
    
    # Update the package list
    sudo apt update -y
    
    # Install Jenkins
    sudo apt-get install jenkins -y
    
    # Start and enable Jenkins
    sudo systemctl start jenkins && sudo systemctl enable jenkins

}

install_jenkins
