#!/bin/bash

function install_zsh(){
# Check if zsh is already installed
if zsh --version &> /dev/null; then
  echo "zsh is already installed."
  exit 0
fi

# Install aptitude if it's not installed
	if ! command -v aptitude &> /dev/null; then
  		apt-get update
  		apt-get install aptitude
	fi

	# Install zsh
	aptitude install zsh
}
