#!/usr/bin/bash

# Installs firewalld on a Debian-based system.

# function install_firewalld
# Installs firewalld on a Debian-based system.
# Returns 0 if successful.
install_firewalld(){
	# Install firewalld using apt-get
	apt-get -y install firewalld
}

install_firewalld
