#!/usr/bin/bash

# Install the .NET 9.0 SDK, which includes the dotnet command and the ASP.NET Core shared framework.
function install_dotnet_9() {
    echo 'Updating package list...'
    sudo apt-get update -qq

    echo 'Installing dotnet-sdk-9.0...'
    sudo apt-get install -y dotnet-sdk-9.0 -qq

    echo 'Install complete.'
}
install_dotnet_9
