#
# Module manifest for module 'PowerNixx'
#
# Generated by: Andres Quesada
#
# Generated on: 3/30/2025
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule           = 'PowerNixx.psm1'

    # Version number of this module.
    ModuleVersion        = '0.0.1'

    # Supported PSEditions
    CompatiblePSEditions = @('Core')

    # ID used to uniquely identify this module
    GUID                 = 'da0bcd8a-9d90-4bb4-bfe6-086a6e05fc9f'

    # Author of this module
    Author               = 'Andres Quesada'

    # Company or vendor of this module
    CompanyName          = 'PowerNixx'

    # Copyright statement for this module
    Copyright            = '(c) Andres Quesada. All rights reserved.'

    # Description of the functionality provided by this module
    Description          = 'PowerNixx: Intelligent Workstation Monitoring'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion    = '7.5'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    #ProcessorArchitecture = 'X64'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules      = @(
        @{
            ModuleName    = 'Microsoft.Powershell.Crescendo'
            ModuleVersion = '1.1.0'            
        },
        @{
            ModuleName    = 'Pode'
            ModuleVersion = '2.12.0'
            Guid          = 'e3ea217c-fc3d-406b-95d5-4304ab06c6af'
        },
        @{
            ModuleName    = 'Pode.Web'
            ModuleVersion = '0.8.3'
        },
        @{
            ModuleName    = 'Pester'
            ModuleVersion = '5.7.1'
        },
        @{
            ModuleName    = 'Psake'
            ModuleVersion = '4.9.1'
        },
        @{
            ModuleName    = 'platyPS'
            ModuleVersion = '0.14.2'
        },
        @{
            ModuleName    = 'Graphical'
            ModuleVersion = '1.0.2'
        },
        @{
            ModuleName    = 'PSScriptAnalyzer'
            ModuleVersion = '1.23.0'
        }
    )

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    #ScriptsToProcess     = @('')

    # Type files (.ps1xml) to be loaded when importing this module
    #TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules        = @(
        'Public/PsNxSystem/PsNxSystem.psm1',
        'Public/PsNxTar/PsNxTar.psm1',
        'Public/PsNxIo/PsNxIo.psm1'
    )

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport    = @(
        'Backup-LogArchive',
        'Build-LlamaCpp',
        'ConvertFrom-DirToTar',
        'ConvertTo-GzipParallel',
        'Copy-OllamaModel',
        'Edit-KittyConfig',
        'Edit-KittyTheme',
        'Find-Package',
        'Format-Df',
        'Format-DiskIO',
        'Format-DiskUsage',
        'Format-JcUsb',
        'Format-Memory',
        'Get-AllPackages',
        'Get-Bios',
        'Get-Branch',
        'Get-BytesPerSecond',
        'Get-CpuArchitecture',
        'Get-CpuFromProc',
        'Get-CpuJson',
        'Get-CpuPercentage',
        'Get-CpuStats',
        'Get-CpuStatus',
        'Get-CpuTemperature',
        'Get-DiskIO',
        'Get-DiskUsage',
        'Get-EthernetAdaptersSpeed',
        'Get-FailedUnits',
        'Get-Hash',
        'Get-Hostnamectl',
        'Get-InstalledPackages',
        'Get-IOStat',
        'Get-Memory',
        'Get-MemorySamplesCount',
        'Get-ModuleMembers',
        'Get-NetStat',
        'Get-Network',
        'Get-NetworkInterfaces',
        'Get-NetworkSentReceived',
        'Get-NetworkStats',
        'Get-NumberedLog',
        'Get-OllamaHelp',
        'Get-OllamaModels',
        'Get-PackageCount',
        'Get-PackageDetails',
        'Get-PowershellHistory',
        'Get-PsModulePaths',
        'Get-RepositoryDetails',
        'Get-RunningModels',
        'Get-System',
        'Get-SystemInfo',
        'Get-SystemUptime',
        'Get-Tree',
        'Get-VarLog',
        'Get-VarLogArchive',
        'Initialize-PsNxCpuSammpler',
        'Install-Homebrew',
        'Install-OllamaModel',
        'Invoke-Df',
        'Invoke-JcUsb',
        'Invoke-PoshThemes',
        'Invoke-Tar',
        'Measure-LogActivity',
        'Measure-PipelinePerformance',
        'New-EncryptionResultObject',
        'New-LogErrorObject',
        'New-PsNxResult',
        'Pop-CrescendoNativeError',
        'Protect-FileWithEncryption',
        'Protect-Repository',
        'Publish-OllamaModel',
        'Push-CrescendoNativeError',
        'Read-JournalBoot',
        'Read-JournalDiskUsage',
        'Read-JournalJson',
        'Read-JournalUser',
        'Read-Log',
        'Read-LogAlternative',
        'Remove-Package',
        'Repair-AllAptitudePackages',
        'Search-DateTimeRange',
        'Search-KeywordInFile',
        'Set-CronPermissions',
        'Set-Suspend',
        'Show-CpuSamples',
        'Show-LiveCpuSamples',
        'Show-LogArchivesLarge',
        'Show-Ollama',
        'Show-OllamaModel',
        'Show-SysLog',
        'Split-LineByNewLine',
        'Split-LinesBySpace',
        'Start-Gemma3Cli',
        'Start-Gemma3LlamaCpp',
        'Start-JournalRotate',
        'Start-Llama3Cli',
        'Start-Ollama',
        'Start-OllamaModel',
        'Stop-Ollama',
        'Stop-OllamaModel',
        'Unprotect-EncryptedFile',
        'Update-Packages',
        'Write-CpuSamples',
        'Write-DirectoryHashes'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport      = @()

    # Variables to export from this module
    VariablesToExport    = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport      = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData          = @{
        PSData = @{
            Tags         = @('Linux', 'Monitoring', 'System', 'Performance', 'Ollama', 'WebUI')
            
            ProjectUri   = 'https://github.com/andmigque/PowerNixx'
            
            LicenseUri   = 'https://github.com/andmigque/PowerNixx/blob/main/LICENSE'
            
            ReleaseNotes = "Initial release`nSystem monitoring functionality`nOllama integration`nWeb UI using Pode.Web"
        }
    }
    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}

